__all__ = ["OK", "MOVED_301", "NO_CONTENT", "UNAUTHORIZED", "FORBIDDEN",
           "INSERTED", "BADPARAMETER", "NOT_FOUND", "NOTACCEPTABLE",
           "WRONG_DATA", "DUPLICATE"]

OK = "200 OK"
INSERTED = "201 CREATED"
NO_CONTENT = "204 NO CONTENT"
MOVED_301 = "301 MOVED PERMANENTLY"
BADPARAMETER = "400 BAD REQUEST"
UNAUTHORIZED = "401 UNAUTHORIZED"
FORBIDDEN = "403 FORBIDDEN"
NOT_FOUND = "404 NOT FOUND"
NOTACCEPTABLE = "406 NOT ACCEPTABLE"
DUPLICATE = "409 CONFLICT"
WRONG_DATA = "422 UNPROCESSABLE ENTITY"